### ISSUE TITLE
Extract 'edit-mode' logic from core as optional plugin

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#17]

**Comment by etiennesegonzac** [comment]
Hey @wilsonpage, do we have something similar in another lib/component?
Wondering how we'd implement a "optional plugin", mixin?

**Comment by wilsonpage** [comment]
You can see how threads.js does [plugins](https://github.com/gaia-components/threads/tree/master/src/plugins/stream).

A 'plugin' is basically a function that gets passed an instance. It's then up to the plugin author to attach event listener, override default functionality or provide new public APIs.

**Comment by wilsonpage** [comment]
Ideally the public API of the class is extensible enough that the plugin author doesn't have a depend on private state/methods, but this may not always be possible.

**Comment by etiennesegonzac** [comment]
I'll have to spend a bit more time to think about the details but I like the approach :)

**Comment by wilsonpage** [comment]
Fixed by 0948d0ef554c8551724aab6fcb18cc1290d65634
