### ISSUE TITLE
Container must be `position: relative | absolute` for scrolling to work

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#20]
We should perhaps enforce this internally.

**Comment by etiennesegonzac** [comment]
Maybe that's a documentation bug :)
But the rendering kinda depends on having absolutely position items.

**Comment by wilsonpage** [comment]
So you're saying we should just tell users to use `relative` or `absolute` on their container?

**Comment by etiennesegonzac** [comment]
yep

**Comment by etiennesegonzac** [comment]
Can we close this one?
