### ISSUE TITLE
Support "chunked list with cached height"

### ISSUE THREAD

**Issue by etiennesegonzac** [gaia-components/fast-list#35]
One of the main gaia use case is probably going to be the following:
- we eventually fetch all the data
- we chunk the fetch and call `reloadData()` for every chunk
- we want to cache and return a complete `fullHeight` to let the user scroll at any point in the list from the get go

We should make this a very happy path :)

**Comment by wilsonpage** [comment]
Is this a job for `<gaia-fast-list>`?

**Comment by wilsonpage** [comment]
Perhaps it could accept a `fullLength` parameter to `.configure()` to make this easy?

**Comment by etiennesegonzac** [comment]
> Is this a job for <gaia-fast-list>?

I think it is :)
Might want to do some tweaks in fast-list, like cancel pending populate requests and all, but that's the idea.
