### ISSUE TITLE
Support a classic search field as part of the list

### ISSUE THREAD

**Issue by etiennesegonzac** [gaia-components/fast-list#38]
For the "raw" `fast-list.js` it's easy
- you put your search field in the dom
- style + add some snapping, since the list uses "native" scrolling it's easy to use css snapping to prevent the field from being "half-openned"
- you offset everything by the height of the field in the datasource (positions + total length)

For the component we'll need
- a config flag for this "padding"
- to move the field's DOM (inside the component) to the container? Not sure about this one...

**Comment by wilsonpage** [comment]
OK I think I understand. Is scroll-snapping supported with APZ? Last time I heard it wasn't, but this may have changed.

**Comment by wilsonpage** [comment]
We also need to start the `scrollTop` at the search field height so it's not visible when the view first loads. Should be fairly trivial though.
