### ISSUE TITLE
Caching V1: Solution for quick subsequent paints

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#47]
After drawing a list once, we can cache the `<li>`s as HTML in `localStorage` and populate the `<gaia-fast-list>` instantly next time it's created.

This means that users on the component don't have to implement their own caching strategies and we can paint something straight away and do some of the more costly initialisation stuff in the background.

**Comment by etiennesegonzac** [comment]
Note: we might want to cache sections/sections height too.
Can be a separate issue if needed, but I'd be cool for the contacts app alphabetical shortcut to work right away (to change the position, the content might load a bit later)
