### ISSUE TITLE
Provide a hook to perform 'secondary' render

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#54]
It is not performant to populate list items with images when scrolling at speed. For this reason we must allow the user to provide a second populate callback that we call only when we think we have time (either scrolling slowly or not at all).

``` js
new FastList({
  populateItem: function(el, i) { ... },
  populateItemDetail: function(el, i) {
    // load images then wait for 'load' and fade in
  }
});
```

To prevent old images showing up in recycled items we need to provide an 'unpoplateItemDetail' hook to give the user a chance to reset the changes they made.

``` js
new FastList({
  ...

  unpopulateItemDetail: function(el, i) {
    // hide <img>s and reset src
  }
});
```

---

In `<gaia-fast-list>` list items should only ever contain one image. This means we can be more opinionated and provide even simpler interface to the user.

``` js
list.configure({
  getImageSrc: function(i) {
    return getImageSrcForItem(i);
  }
});
```

Behind the scenes we can take care of setting the given `src`, fading-in the image on `'load'` and then cleaning up. This work should all be done when app is 'relatively' idle (slow or stopped scrolling), so performance isn't as much of a concern as it would be with `populateItem()`.

@etiennesegonzac any thoughts to add?

**Comment by etiennesegonzac** [comment]
Like the naming!
It's internal to the list but we need to make sure there's never a race between `populateItemDetail` / `unpopulateItemDetail` and "delayed" populateItem (the ones that return a promise).
