### ISSUE TITLE
[flame] Painting the list takes > 150ms 

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#55]
<img width="1083" alt="screen shot 2015-09-08 at 11 49 41" src="https://cloud.githubusercontent.com/assets/1020551/9732957/cac11890-561f-11e5-9d9f-d1669ea4b6ba.png">

**Comment by wilsonpage** [comment]
Captured by toggling the visibility of the scrolling element.

**Comment by wilsonpage** [comment]
I think we need help from platform graphics to help us speed this up.

**Comment by wilsonpage** [comment]
[Profile](https://people.mozilla.org/~bgirard/cleopatra/#report=128e4a87434a0e918cc52dadec7911d92e79ccfb) of startup of [examples/gaia-fast-list/simple](https://github.com/gaia-components/fast-list/tree/master/examples/gaia-fast-list/simple). Suggests we're spending ~700ms in paint.

**Comment by wilsonpage** [comment]
[Profile of scrolling](https://people.mozilla.org/~bgirard/cleopatra/#report=acc3a207e0d503ff5b1149ce8d825d79f0fc0ff6) app examples/gaia-fast-list/caching.

When the profiler was running it seemed to completely block painting, so the list would scroll but appear blank for several seconds, then paint.

**Comment by wilsonpage** [comment]
I tried reducing the interval to `-i 10` but this didn't appear to have any impact.

**Comment by wilsonpage** [comment]
Got a [better profile of scrolling](https://people.mozilla.org/~bgirard/cleopatra/#report=2ec5cb5ea854e01fef284bb5970d6f1d1e7dbe60&selection=0,1046,1047,1048,9). Mason says that painting isn't the bottleneck but 'display list processing'.

**Comment by mattwoodrow** [comment]
I assume you mean that asynchronous scrolling is still working? As in, scrolling happens immediately and fluidly, but the scrolled in content can sometimes be blank and take a while to appear.

The profile indeed shows display list building and processing to be taking up huge amounts of time, painting itself seems to be fast.

These two processes generally scale linearly as the number of display items (border, background, text run etc) increases. We are in the process of starting some projects to improve this, but these won't be short term fixes.

The profile doesn't really show anything interesting under these two heading (though we don't have full stacks). It looks like we just have a lot of items, and the cost is adding up.

Is the content here particularly complicated/dense? The 'layout.display-list.dump' pref causes the display list to be dumped to stdout (works well on desktop, unsure about fxOS), and would be useful to get an idea of what is taking so long.

**Comment by wilsonpage** [comment]
[This profile](https://people.mozilla.org/~bgirard/cleopatra/#report=73c088166965e083d4aa0d993e7d49fec21768f8) is profiling startup and includes c++ stack traces.

**Comment by wilsonpage** [comment]
FYI the web-component `<gaia-fast-list>` has recently moved to its [own repo](https://github.com/gaia-components/gaia-fast-list) and depends on `fast-list.js` (this repo).

**Comment by wilsonpage** [comment]
[Profile](https://people.mozilla.org/~bgirard/cleopatra/#report=fa961fda3c5ca71bd8bf57c2b354355dd88b3831) of scrolling with cc+ stacktraces and display-list dump

**Comment by wilsonpage** [comment]
[Profile](https://people.mozilla.org/~bgirard/cleopatra/#report=c8eecc894812b9422c919968c8d753282597993a) of startup with cc+ stacktraces and display-list dump
