### ISSUE TITLE
[gaia-fast-list] Add optional alphabet picker column

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#56]

**Comment by wilsonpage** [comment]
Does it make sense for this to be letter picker only, or should we make it more extensible than that?

**Comment by etiennesegonzac** [comment]
It's tricky. Would there be any other "1 letter use case" than letter picker.
And if we need to show all letter regardless of the sections then we have to go specific.

**Comment by wilsonpage** [comment]
> we have to go specific

?

**Comment by etiennesegonzac** [comment]
by "go specific" I meant "make it really specific and not extensible"

**Comment by wilsonpage** [comment]
Ah gotcha, good point. Let's just make this an opinionated alphabetical picker :)

**Comment by wilsonpage** [comment]
Migrated to https://github.com/gaia-components/gaia-fast-list/issues/1
