### ISSUE TITLE
Emptying data-source and .reloadData() doesn't empty list

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#69]
There are cases when the number of items in the data-source could be reset to less than the number of `<li>`s rendered. In this case we are not removing unneeded `<li>`s from the DOM. Giving the impression that the list hasn't been re-rendered.

**Comment by wilsonpage** [comment]
See also: https://github.com/gaia-components/gaia-fast-list/issues/12

**Comment by etiennesegonzac** [comment]
Will work on it tomorrow hopefully.
