### ISSUE TITLE
populateItemDetail() is never called after scrollInstantly()

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/fast-list#76]
After running `.scrollInstantly()` fast-list is flagged as `!idle` so `.populateItemDetail()` is never run. This is also the case when scrolling fast and then tapping the list to halt scrolling.

It seems we need to implement some logic that always runs `.popuateItemDetail()` once scrolling has finished.

Any suggestions @etiennesegonzac?

**Comment by etiennesegonzac** [comment]
We still have the "tap to stop" issue. So this is rightfully still open.
