### ISSUE TITLE
Sticky headers are broken

### ISSUE THREAD

**Issue by etiennesegonzac** [gaia-components/fast-list#85]
Because of https://github.com/gaia-components/fast-list/blob/de07ebcaa0ca7334769ec3aae3ff302b68e0c34a/fast-list.js#L45

We need to fix it without breaking variable height support.

I'll get to it, but probably not today.

**Comment by wilsonpage** [comment]
I vote we `display: none` the list-items that aren't required. We usually have to perform a significant reflow when updating the list any way. But I might be overlooking something :)

**Comment by etiennesegonzac** [comment]
My instinct was to start with `visibility:hidden`, but the list scrollable area will always be `>= maxItemsCount * itemHeight`.

If we go display:none we'll need to have a separate code path for the (legacy) "new content" support and this too.

**Comment by etiennesegonzac** [comment]
The code paths are actually separated enough :)
`display:none` it is!
